# This workflow will build a docker container, publish it to Google Container
# Registry, and deploy it to GKE when there is a push to the "main"
# branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Google Kubernetes Engine (container.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Ensure that your repository contains the necessary configuration for your
#    Google Kubernetes Engine cluster, including deployment.yml,
#    kustomization.yml, service.yml, etc.
#
# 3. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Kubernetes Engine Developer (roles/container.developer)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources
#
# 5. Change the values in the "env" block to match your values.

name: 'T2E - Build and Deploy to EKS'

on:
  push:
    branches:
      - "feature-*"

env:
  DEPLOYMENT_NAME: 't2e-dev' # TODO: update to your deployment name
  REPOSITORY: 't2e' # TODO: update to your Artifact Registry docker repository name
  IMAGE: 't2e-dev'

jobs:
  build:
    name: 'BUILD'
    runs-on: 'ubuntu-latest'
    environment: 'dev'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - name: Set short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Build the Docker image
      - name: 'Build and push Docker container'
        run: |-
          DOCKER_TAG="t2e:${SHORT_SHA}"

          docker build \
            --tag "${DOCKER_TAG}" .

          # DOOCKER IMAGE ON DISK --- TAGGED WITH NAME:TAG (t2e:abc123)
          ## docker push "${DOCKER_TAG}"

      #Disabled last command of deploy
  deploydev:
    name: 'DEPLOY'
    runs-on: 'ubuntu-latest'
    steps:
      - name: deploy
        run: echo "deploying.."
